CREATE TABLE [LDAPHUNTERFINDINGS] ( 
	[FindingId] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
	[DistinguishedName] NVARCHAR(300)  NOT NULL,
        [AttributeName] NVARCHAR(100) NOT NULL, 
        [Value] NVARCHAR(300) NOT NULL,
        [Domain] NVARCHAR(200) NOT NULL  
); 
